modLoader="javafml"
loaderVersion="[47,)"
license="GNU LGPLv3"
issueTrackerURL="https://github.com/holmraven/ChickensShed/issues"

[[mods]]
modId="chickensshed"
version="${version}"
displayName="ChickensShed"
displayURL="https://modrinth.com/mod/chickensshed"
logoFile="icon.png"
authors="holmraven"

description='''Chickens shed their feathers occasionally.'''
[[dependencies.chickensshed]]
    modId="forge"
    mandatory=true
    versionRange="[47.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.chickensshed]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.chickensshed]]
    modId="cloth_config"
    mandatory=false
    versionRange="[11,)"
    ordering="NONE"
    side="BOTH"
